ukrgb_oauth_route:
    path: /oauth/{name}
    defaults: { _controller: ukrgb.oauth.controller:handle }
    
    
ukrgb_oauth_register:
    path: /oauth/register
    defaults: { _controller: ukrgb.oauth.controller:handle }
    