services:
    ukrgb.oauth.controller:
        class: ukrgb\oauth\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
    ukrgb.oauth.listener:       # name of the service you want to register
        class: ukrgb\oauth\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }