services:
    ukrgb.oauth.controller:
        class: ukrgb\oauth\controller\main
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@passwords.manager'
            - '@request'
            - '@user'
            - '%tables.auth_provider_oauth_token_storage%'
            - '%tables.auth_provider_oauth_account_assoc%'
            - '@auth.provider.oauth.service_collection'
            - '%tables.users%'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
            
            
    ukrgb.oauth.listener:     
        class: ukrgb\oauth\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
            
            