services:
    ukrgb.jfusion.listener:
        class: ukrgb\jfusion\event\main_listener
        arguments:
            - @config
            - @user
            - @request
            - %core.root_path%
            - %core.php_ext%
                        
        tags:
            - { name: event.listener }
