services:
     ukrgb.template.listener:       # name of the service you want to register
        class: ukrgb\template\event\main_listener
        arguments:
            - '@template'
            - '@cache.driver'
            - '@config'

        tags:
            - { name: event.listener }