services:
     ukrgb.fix.listener:       # name of the service you want to register
        class: ukrgb\fix\event\main_listener
        arguments:
                    - '@user'
        tags:
            - { name: event.listener }